title: aiotter's blog
email: mail@aiotter.com
description: >- # this means to ignore newlines until "baseurl:"
  aiotter's blog about technology and otters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aiotter.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: aiotter/website
branch: master
twitter_username: aiotter_tech
github_username: aiotter
permalink: /:slug/

# make `_pages` look like a root dir
collections:
  pages:
    output: true
    permalink: /:path/

# Build settings
theme: plainwhite
plugins:
  - jekyll-asciidoc
  - asciidoctor-diagram
  - jekyll-feed
  - jekyll-archives

plainwhite:
  name: aiotter
  tagline: 技術とカワウソ
  date_format: "%Y/%m/%d"

  social_links:
    twitter: aiotter_tech
    github: aiotter
    # linkedIn: in/samarsault # format: locale/username

  portfolio_image: "img/icon.png"
  disqus_shortname: aiotter
  sitemap: true
  html_lang: "ja"

  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"

keep_files:
  - img
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - imagesdir=/img
    - source-highlighter=pygments
    - source-linenums-option
    - pygments-css=style
    - pygments-style=monokai
    - icons=font
    - idseparator=-


jekyll-archives:
  enabled: [tags, categories]
