title: aiotter's blog
email: mail@aiotter.com
description: >- # this means to ignore newlines until "baseurl:"
  aiotter's blog about technology and otters.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aiotter.com" # the base hostname & protocol for your site, e.g. http://example.com
repogitory_prefix: https://github.com/aiotter/website/blob/master
twitter_username: aiotter_tech
github_username: aiotter
permalink: /:slug/

# Build settings
theme: plainwhite
plugins:
  - jekyll-asciidoc
  - jekyll-feed

plainwhite:
  name: aiotter
  tagline: 技術とカワウソ
  date_format: "%Y/%m/%d"

  social_links:
    twitter: aiotter_tech
    github: aiotter
    # linkedIn: in/samarsault # format: locale/username

  portfolio_image: "img/icon.png"
  disqus_shortname: aiotter
  sitemap: true
  html_lang: "ja"

  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"

asciidoc: {}
asciidoctor:
  attributes:
    - source-highlighter=pygments
    - source-linenums-option
    - pygments-css=style
    - pygments-style=monokai
    - icons=font
    - idseparator=_
