[[redirects]]
  from = "/starting-blog-with-jekyll"
  to = "/tech/starting-blog-with-jekyll"

[[redirects]]
  from = "/lets-deoplete"
  to = "/tech/lets-deoplete"

[[redirects]]
  from = "/github-comment-system"
  to = "/tech/github-comment-system"

[[redirects]]
  from = "/netlify-trap"
  to = "/tech/netlify-trap"
