= Jekyll でブログを始めました

== なぜ Hugo を使わなかったのか
私は https://ocsj.asia[日本アジアカワウソ保全協会] の技術担当として，Hugo でウェブサイトの保守をしています．
Hugo は Go で実装された静的サイトジェネレータで，極めて高速なので執筆からプレビューまでの時間が無視できるほど短く，とても便利です．

今回個人用のブログを立ち上げるにあたっても最初は Hugo で作ろうとしたのですが， AsciiDoc で書いた記事をうまくビルドできない問題に遭遇し，仕方なく Hugo の利用を諦めました．

== なぜ Markdown ではなく AsciiDoc なのか
AsciiDoc は Markdown と同じ軽量マークアップ言語です．
Markdown よりはるかに表現力があり，相互参照や図表番号など，真面目な書類を作るのに必要な道具が一通り揃っています．

TIP: 例えばこの段落は Admonition という構文で，AsciiDoc の仕様で定義されています．

Markdown にも独自に言語仕様の拡張をすることで表現力を高めてブログなどでも使いやすくした例がありますが，そのせいで方言が乱立してしまっている状態です．
(特に Pandoc の Markdown 拡張は非常に混乱します)

一方，AsciiDoc は素の状態で表現力が高いだけではなく，言語仕様を拡張する方法がプラグインとして仕様化されています．
したがって方言が乱立する問題が起こりません．

Markdown は複雑な構造を持たない議事録などの文章を作成するにはもってこいのツールですが，なんでもかんでも Markdown を使おうという流れには私は反対です．
脚注や相互参照が必要になるような技術ブログは AsciiDoc や reStructuredText などのより表現力があるマークアップ言語が適切だと思います．

NOTE: *reStructuredText* は表現力があるマークアップ言語です．
コンパクトに多くの情報が書ける利点があり，Python の Docstring でよく利用されています． +
可読性が下がりがちで直感的に書きにくく感じるため，ブログ用途には採用しませんでした．


== Hugo で発生した問題
=== ソースコードが正常に表示できなかった
Hugo がソースコードに対して行うコードハイライトと， asciidoctor footnote:[AsciiDoc の Ruby 実装] が行うコードハイライトが衝突して，コードが正常に表示されない状態になってしまいました．
CSS で無理やり解決しても良かったのですが，コード内にコメントを書き込む構文などの整合性を取るのが困難で諦めました．

=== Front matter を付ける必要があった
Hugo はメタデータを
Front matter footnote:[記事ファイルの一番最初に yaml などで書き込むメタデータ群． https://github.com/khos2ow/hugo-wrapper/blob/25dafe3aa2ec78716e716595bdc48226e44128fb/example/content/blog/creating-a-new-theme.md[一例]]
で管理していますが，これは AsciiDoc の独自拡張にあたるため，Front matter を付けると asciidoctor が正常に処理できないファイルになってしまいます．

記事を単体で PDF にしたり，HTML にしてプレビューしたりといったことができなくなり，再利用性が下がるため，
Front matter を使わずに管理できないかと考えて試行錯誤しました．

Front matter なしでも slug footnote:[URL の一部に使う文字列] や記事作成日はファイル名から読み取らせることができたのですが，
ページタイトルを見出しから生成する手段は存在しないため，Front matter なしで運用することは不可能だと分かりました．

== Jekyll が適していた理由
asciidoctor が Jekyll 用のプラグインを公開していて，更新が頻繁に行われていたことが決め手になりました．

Hugo はあくまでも Hugo 側が asciidoctor を呼び出しその成果物を利用する形でした．
Jekyll の場合は，asciidoctor の開発者が Jekyll で使うためのプラグインを提供している形です．
これは期待できると思って Jekyll を使うことにしました．

なお，Gatsby も試してみようと思ったのですが，フロントエンドのことが何も分からないので断念しました．

== まとめ
Jekyll with AsciiDoc はとても書きやすく便利です！
これから頑張ってブログ更新していこうと思います！
