= GitHub を利用した新しいコメントシステムを実装しました
:page-category: Tech
:page-tags: [JavaScript, Blog]

GitHub って特定のコミットに対してコメントする機能があるじゃないですか．
これを技術ブログのコメントに流用したら，どのバージョンに対するコメントなのかがはっきりしてめっちゃ便利なんじゃないかと思いました．ので，このブログのコメント機能として実装してみました．

== どんなもんよ
この記事を一番下までスクロールするとそこにあります．
テスト代わりに書き込んでみてもいいですよ．
気に入ったら真似してくださっても結構です．

== システム概要
仕組みとしては単純で，GitHub の２つの API を組み合わせただけです．

- https://docs.github.com/en/rest/reference/repos#list-commits[List commits]
- https://docs.github.com/en/rest/reference/repos#list-commit-comments-for-a-repository[List commit comments for a repository]

前者は特定のリポジトリのコミット履歴を一覧で取得するものですが，パラメタで指定すると，特定のファイルへの変更を含むものだけを抽出できます．
後者は特定のリポジトリに存在するコミットコメントを一覧で取得できます．

この２つを組み合わせることで，ウェブサイトを管理するリポジトリのコミットコメントのうち，閲覧中の記事に関連するもののみを一覧で取得することができます．


== 開発四方山話
私は JavaScript に対する忌避感が強くて，いくらでもヤバい書き方ができてしまう闇黒な言語だと思っていました．

モダンで明確な書き方もできるだろうとは思っていましたが，初学者の私にはどれが良い書き方でどれがヤバい書き方なのか区別できる自信がなかったので，信頼できる良い教材が見つかれば勉強してみようかなあくらいの気持ちでずっと過ごしてきました．
友人の https://github.com/kirisaki[@kirisaki] さんに https://jsprimer.net/[JavaScript Primer] を教えてもらったので，重い腰を上げてちょっと勉強してみたら，案外簡単に書けました．

これからは JavaScript とも適度な距離感を保ちながら仲良くして行こうと思います．
私は JavaScript とかよりも Julia とか Rust とかがやりたいんだよなあ．


== 課題
2 種類の API のうちどちらも，一回のリクエストでは同時に 100 件のコミットコメントなりコミットなりしか取得できません．

まあひとつの記事を 100 回も書き直すことはまずないのでコミットの方はどうでもいいんですが，コミットコメントの方はリポジトリ全体で 100 件が限界なので，このブログへの累計コメント数が 100 件に達する前にページネーションを実装する必要があります．

そのうちやる気が出たらやります．でもその前に CSS のヤバさをなんとかしないといけない……
