name: ci

on:
  push:
    branches:
      - lume
  pull_request:
    branches:
      - lume

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: deno-sass
        with:
          path: _bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Makefile') }}

      - name: Build site
        run: make build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: aiotter-blog
          entrypoint: _server/main.ts
