name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DENO_DIR: .deno

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: deno-tailwind
        with:
          path: _bin
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Makefile') }}

      - name: Cache deno libraries
        uses: actions/cache@v2
        env:
          cache-name: deno-dir
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Build site
        run: make build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: aiotter-blog
          entrypoint: _server/main.ts

      - name: Purge cache on Cloudflare
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
